env:
  browser: true
  es6: true
  node: true
parser: vue-eslint-parser
parserOptions:
  parser: babel-eslint
  ecmaVersion: 2020
  sourceType: module
plugins:
  - vue
  - prettier
extends:
  - eslint:recommended
  - plugin:vue/recommended
  - plugin:prettier/recommended
  - prettier/vue
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      htmlWhitespaceSensitivity: ignore
  vue/max-attributes-per-line:
    - error
    - singleline: 5
      multiline:
        max: 1
        allowFirstLine: false
